# Generated by Django 5.2.14 on 2026-05-19 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baggage_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('short_link', models.URLField()),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='arrival_trips', to='jastip.airport')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='departure_trips', to='jastip.airport')),
            ],
        ),
    ]
