# Generated by Django 5.2.14 on 2026-05-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jastip', '0002_alter_trip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
